### ISSUE TITLE
Integration on OSX with the M1 chip (arm64)?

### ISSUE THREAD

**Issue by BoltzmannEntropy** [PaddlePaddle/Quantum#40]
Hello,
Is there a version for OSX with the M1 chip?

Thanks,

**Comment by BoltzmannEntropy** [comment]
Hello, the x86 version works without a GPU? 

Thanks,

**Comment by wangzihe1996** [comment]
It's slightly complicated. You can refer to ["Use Paddle Quantum on GPU"](https://qml.baidu.com/quick-start/use-paddle-quantum-on-gpu.html). In briefly, you need to install `paddlepaddle-gpu` and `paddle-quantum`. You can read [this document](https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/macos-pip_en.htmll) to know how to install `paddlepaddle-gpu`.

**Comment by wangzihe1996** [comment]
You just need to `pip install paddle-quantum`, which installs the CPU version by default.

**Comment by BoltzmannEntropy** [comment]
@wangzihe1996 this does NOT work on OSX, which was my original question. 
Is there a way to install the CPU version on OSX M1 chip?!

**Comment by BoltzmannEntropy** [comment]
Anyone?

**Comment by CloudwinZL48** [comment]
Hello. Following the instructions in the [installation guide](https://qml.baidu.com/install/installation_guide.html), the Paddle Quantum should work properly with OSX M1 chip under the ``x86_64`` version of anaconda. 

There are many reasons for faling to install packages with OSX M1 chip. One possible explanation is that your Python virtual environment has already been contaminated. You may need to specify more details (like how it did not work) so that further assistances can be adviced.

**Comment by BoltzmannEntropy** [comment]
I ended up creating a docker: https://github.com/BoltzmannEntropy/QMLDocker
